### ISSUE TITLE
error with Menu

### ISSUE THREAD

**Issue by gingerlime** [fyhuang/choice#1]
Trying the example on the readme with the menu produces an error:

`TypeError: Menu() takes at least 2 arguments (1 given)`

Not sure what's `choices` and what's `actions`, and why do you need both??

Otherwise this is a cute idea. Would be nice to have a default value for Input, e.g.

`choice.Input('favourite colour [green]:', str, 'green')`

**Comment by fyhuang** [comment]
Hi gingerlime, thanks for your comments! I fixed the Menu issue, also fixed a small typo in the README relating to that (don't forget to call `ask()` after creating). Cheers!
